# generated by datamodel-codegen:
#   filename:  contracts.schema.json

from __future__ import annotations

from enum import Enum, StrEnum
from typing import Annotated, Literal
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Ref(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    revision: Annotated[int, Field(ge=1)]


class Tier(StrEnum):
    DOCUMENTED = 'DOCUMENTED'
    OBSERVED = 'OBSERVED'
    INFERRED = 'INFERRED'
    SPECULATIVE = 'SPECULATIVE'


class Origin(StrEnum):
    HUMAN = 'HUMAN'
    EXTRACTED = 'EXTRACTED'
    AI_SYNTHETIC = 'AI_SYNTHETIC'


class Review(StrEnum):
    PENDING = 'PENDING'
    ACCEPTED = 'ACCEPTED'
    REJECTED = 'REJECTED'


class Raw(RootModel[str]):
    root: Annotated[str, Field(max_length=20000, min_length=1)]


class Timezone(RootModel[str]):
    root: Annotated[str, Field(max_length=200, min_length=1)]


class Precision(StrEnum):
    EXACT = 'EXACT'
    RANGE = 'RANGE'
    APPROXIMATE = 'APPROXIMATE'
    DATE_ONLY = 'DATE_ONLY'
    UNKNOWN = 'UNKNOWN'
    DISPUTED = 'DISPUTED'


class ToleranceSeconds(RootModel[int]):
    root: Annotated[int, Field(ge=0)]


class Time(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    raw: Raw | None
    start: AwareDatetime | None
    end: AwareDatetime | None
    start_inclusive: bool
    end_inclusive: bool
    timezone: Timezone | None
    precision: Precision
    clock_source: Annotated[str, Field(max_length=200, min_length=1)]
    tolerance_seconds: ToleranceSeconds | None
    alternative_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]


class Locator1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['text']
    start: Annotated[int, Field(ge=0)]
    end: Annotated[int, Field(ge=0)]


class BboxItem(RootModel[float]):
    root: Annotated[float, Field(ge=0.0, le=1.0)]


class Bbox(RootModel[list[BboxItem]]):
    root: Annotated[list[BboxItem], Field(max_length=4, min_length=4)]


class Locator2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['page']
    page: Annotated[int, Field(ge=1)]
    bbox: Bbox | None


class Sheet(RootModel[str]):
    root: Annotated[str, Field(max_length=200, min_length=1)]


class Column(RootModel[str]):
    root: Annotated[str, Field(max_length=200, min_length=1)]


class Locator3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['row']
    sheet: Sheet | None
    row: Annotated[int, Field(ge=1)]
    column: Column | None


class Locator4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['media']
    start_ms: Annotated[int, Field(ge=0)]
    end_ms: Annotated[int, Field(ge=0)]


class Locator(RootModel[Locator1 | Locator2 | Locator3 | Locator4]):
    root: Locator1 | Locator2 | Locator3 | Locator4


class DerivativeSha256(RootModel[str]):
    root: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]


class Quote(RootModel[str]):
    root: Annotated[str, Field(max_length=20000, min_length=1)]


class Citation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    evidence: Ref
    evidence_sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]
    derivative: Ref | None
    derivative_sha256: DerivativeSha256 | None
    locator: Locator
    quote: Quote | None


class Case(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    title: Annotated[str, Field(max_length=200, min_length=1)]
    timezone: Annotated[str, Field(max_length=200, min_length=1)]
    schema_version: Literal['1.0.0']
    case_revision: Annotated[int, Field(ge=0)]
    synthetic: bool
    created_at: AwareDatetime


class SourceChannel(StrEnum):
    UPLOAD = 'UPLOAD'
    MANUAL = 'MANUAL'
    CASEMAIL = 'CASEMAIL'
    IMPORT = 'IMPORT'


class Integrity(StrEnum):
    PENDING = 'PENDING'
    VERIFIED = 'VERIFIED'
    FAILED = 'FAILED'


class ScanStatus(StrEnum):
    UNSCANNED = 'UNSCANNED'
    CLEAN = 'CLEAN'
    QUARANTINED = 'QUARANTINED'


class Evidence(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    case_id: UUID
    revision: Annotated[int, Field(ge=1)]
    introduced_case_revision: Annotated[int, Field(ge=0)]
    created_at: AwareDatetime
    created_by: Annotated[str, Field(max_length=200, min_length=1)]
    kind: Literal['Evidence']
    sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]
    bytes: Annotated[int, Field(ge=0)]
    media_type: Annotated[str, Field(max_length=200, min_length=1)]
    original_filename: Annotated[str, Field(max_length=200, min_length=1)]
    received_at: AwareDatetime
    source_channel: SourceChannel
    integrity: Integrity
    scan_status: ScanStatus


class DerivativeType(StrEnum):
    TEXT = 'TEXT'
    OCR = 'OCR'
    PREVIEW = 'PREVIEW'
    REDACTED = 'REDACTED'
    TRANSCRIPT = 'TRANSCRIPT'
    LOCATOR_MAP = 'LOCATOR_MAP'


class Derivative(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    case_id: UUID
    revision: Annotated[int, Field(ge=1)]
    introduced_case_revision: Annotated[int, Field(ge=0)]
    created_at: AwareDatetime
    created_by: Annotated[str, Field(max_length=200, min_length=1)]
    kind: Literal['Derivative']
    evidence: Ref
    sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]
    bytes: Annotated[int, Field(ge=0)]
    derivative_type: DerivativeType
    tool: Annotated[str, Field(max_length=200, min_length=1)]
    tool_version: Annotated[str, Field(max_length=200, min_length=1)]
    config_sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]
    media_type: Annotated[str, Field(max_length=200, min_length=1)]


class EntityType(StrEnum):
    PERSON = 'PERSON'
    ORGANIZATION = 'ORGANIZATION'
    PLACE = 'PLACE'
    OBJECT = 'OBJECT'
    VEHICLE = 'VEHICLE'
    DEVICE = 'DEVICE'
    UNKNOWN_ACTOR = 'UNKNOWN_ACTOR'


class Alias(RootModel[str]):
    root: Annotated[str, Field(max_length=200, min_length=1)]


class Entity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    case_id: UUID
    revision: Annotated[int, Field(ge=1)]
    introduced_case_revision: Annotated[int, Field(ge=0)]
    created_at: AwareDatetime
    created_by: Annotated[str, Field(max_length=200, min_length=1)]
    kind: Literal['Entity']
    label: Annotated[str, Field(max_length=200, min_length=1)]
    entity_type: EntityType
    aliases: Annotated[list[Alias], Field(max_length=10000, min_length=0)]
    review: Review
    source_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]


class Origin1(StrEnum):
    HUMAN = 'HUMAN'
    EXTRACTED = 'EXTRACTED'


class Independence(StrEnum):
    UNKNOWN = 'UNKNOWN'
    SHARED = 'SHARED'
    REVIEWED_INDEPENDENT = 'REVIEWED_INDEPENDENT'


class Observation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    case_id: UUID
    revision: Annotated[int, Field(ge=1)]
    introduced_case_revision: Annotated[int, Field(ge=0)]
    created_at: AwareDatetime
    created_by: Annotated[str, Field(max_length=200, min_length=1)]
    kind: Literal['Observation']
    tier: Tier
    origin: Origin1
    review: Review
    citations: Annotated[list[Citation], Field(max_length=10000, min_length=1)]
    support_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    counter_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    rationale: Annotated[str, Field(max_length=20000, min_length=1)]
    statement: Annotated[str, Field(max_length=20000, min_length=1)]
    subject_refs: Annotated[list[Ref], Field(max_length=10000, min_length=1)]
    predicate: Annotated[str, Field(max_length=200, min_length=1)]
    object_value: Annotated[str, Field(max_length=20000, min_length=1)]
    occurrence: Time
    discovered_at: AwareDatetime | None
    recorded_at: AwareDatetime | None
    provenance_group: Annotated[str, Field(max_length=200, min_length=1)]
    independence: Independence


class Assumption(RootModel[str]):
    root: Annotated[str, Field(max_length=20000, min_length=1)]


class Interpretation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    case_id: UUID
    revision: Annotated[int, Field(ge=1)]
    introduced_case_revision: Annotated[int, Field(ge=0)]
    created_at: AwareDatetime
    created_by: Annotated[str, Field(max_length=200, min_length=1)]
    kind: Literal['Interpretation']
    tier: Tier
    origin: Origin
    review: Review
    citations: Annotated[list[Citation], Field(max_length=10000, min_length=0)]
    support_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    counter_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    rationale: Annotated[str, Field(max_length=20000, min_length=1)]
    statement: Annotated[str, Field(max_length=20000, min_length=1)]
    assumptions: Annotated[list[Assumption], Field(max_length=10000, min_length=0)]
    premise_refs: Annotated[list[Ref], Field(max_length=10000, min_length=1)]


class Event(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    case_id: UUID
    revision: Annotated[int, Field(ge=1)]
    introduced_case_revision: Annotated[int, Field(ge=0)]
    created_at: AwareDatetime
    created_by: Annotated[str, Field(max_length=200, min_length=1)]
    kind: Literal['Event']
    tier: Tier
    origin: Origin
    review: Review
    citations: Annotated[list[Citation], Field(max_length=10000, min_length=0)]
    support_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    counter_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    rationale: Annotated[str, Field(max_length=20000, min_length=1)]
    label: Annotated[str, Field(max_length=200, min_length=1)]
    occurrence: Time
    participant_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    observation_refs: Annotated[list[Ref], Field(max_length=10000, min_length=1)]


class Relation(StrEnum):
    MENTIONS = 'MENTIONS'
    LOCATED_AT = 'LOCATED_AT'
    PARTICIPATED_IN = 'PARTICIPATED_IN'
    SUPPORTS = 'SUPPORTS'
    CONTRADICTS = 'CONTRADICTS'
    PRECEDES = 'PRECEDES'
    REFERS_TO = 'REFERS_TO'
    SAME_IDENTIFIER = 'SAME_IDENTIFIER'


class Edge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    case_id: UUID
    revision: Annotated[int, Field(ge=1)]
    introduced_case_revision: Annotated[int, Field(ge=0)]
    created_at: AwareDatetime
    created_by: Annotated[str, Field(max_length=200, min_length=1)]
    kind: Literal['Edge']
    tier: Tier
    origin: Origin
    review: Review
    citations: Annotated[list[Citation], Field(max_length=10000, min_length=0)]
    support_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    counter_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    rationale: Annotated[str, Field(max_length=20000, min_length=1)]
    from_ref: Ref
    to_ref: Ref
    relation: Relation
    independence: Independence


class Strength(StrEnum):
    POTENTIAL = 'POTENTIAL'
    LOGICAL = 'LOGICAL'


class Status(StrEnum):
    CANDIDATE = 'CANDIDATE'
    UNRESOLVED = 'UNRESOLVED'
    RESOLVED = 'RESOLVED'
    DISMISSED = 'DISMISSED'


class Qualification(RootModel[str]):
    root: Annotated[str, Field(max_length=20000, min_length=1)]


class ResolutionTarget(RootModel[str]):
    root: Annotated[str, Field(max_length=20000, min_length=1)]


class DecisionReason(RootModel[str]):
    root: Annotated[str, Field(max_length=20000, min_length=1)]


class Contradiction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    case_id: UUID
    revision: Annotated[int, Field(ge=1)]
    introduced_case_revision: Annotated[int, Field(ge=0)]
    created_at: AwareDatetime
    created_by: Annotated[str, Field(max_length=200, min_length=1)]
    kind: Literal['Contradiction']
    proposition_refs: Annotated[list[Ref], Field(max_length=20, min_length=2)]
    rule: Annotated[str, Field(max_length=200, min_length=1)]
    rule_version: Annotated[str, Field(max_length=200, min_length=1)]
    strength: Strength
    status: Status
    qualifications: Annotated[
        list[Qualification], Field(max_length=10000, min_length=0)
    ]
    resolution_targets: Annotated[
        list[ResolutionTarget], Field(max_length=10000, min_length=1)
    ]
    resolution_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    decision_reason: DecisionReason | None
    predecessor_id: UUID | None


class State(StrEnum):
    PROPOSED = 'PROPOSED'
    TESTING = 'TESTING'
    SUPPORTED = 'SUPPORTED'
    WEAKENED = 'WEAKENED'
    RETIRED = 'RETIRED'


class StrengthenIfItem(RootModel[str]):
    root: Annotated[str, Field(max_length=20000, min_length=1)]


class WeakenIfItem(RootModel[str]):
    root: Annotated[str, Field(max_length=20000, min_length=1)]


class RetireIfItem(RootModel[str]):
    root: Annotated[str, Field(max_length=20000, min_length=1)]


class Falsifiability(StrEnum):
    TESTABLE = 'TESTABLE'
    NOT_CURRENTLY_FALSIFIABLE = 'NOT_CURRENTLY_FALSIFIABLE'


class RetirementReason(RootModel[str]):
    root: Annotated[str, Field(max_length=20000, min_length=1)]


class RetiredAtCaseRevision(RootModel[int]):
    root: Annotated[int, Field(ge=0)]


class Hypothesis(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    case_id: UUID
    revision: Annotated[int, Field(ge=1)]
    introduced_case_revision: Annotated[int, Field(ge=0)]
    created_at: AwareDatetime
    created_by: Annotated[str, Field(max_length=200, min_length=1)]
    kind: Literal['Hypothesis']
    tier: Tier
    origin: Origin
    review: Review
    citations: Annotated[list[Citation], Field(max_length=10000, min_length=0)]
    support_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    counter_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    rationale: Annotated[str, Field(max_length=20000, min_length=1)]
    claim: Annotated[str, Field(max_length=20000, min_length=1)]
    state: State
    family_key: Annotated[str, Field(max_length=200, min_length=1)]
    strengthen_if: Annotated[
        list[StrengthenIfItem], Field(max_length=10000, min_length=0)
    ]
    weaken_if: Annotated[list[WeakenIfItem], Field(max_length=10000, min_length=0)]
    retire_if: Annotated[list[RetireIfItem], Field(max_length=10000, min_length=0)]
    falsifiability: Falsifiability
    retirement_reason: RetirementReason | None
    retired_at_case_revision: RetiredAtCaseRevision | None
    predecessor_id: UUID | None
    reopening_evidence: Annotated[list[Ref], Field(max_length=10000, min_length=0)]


class Outcome(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    observation: Annotated[str, Field(max_length=20000, min_length=1)]
    supports_scenario_ids: Annotated[list[UUID], Field(max_length=10000, min_length=0)]
    weakens_scenario_ids: Annotated[list[UUID], Field(max_length=10000, min_length=0)]


class Limitation(RootModel[str]):
    root: Annotated[str, Field(max_length=20000, min_length=1)]


class Effort(StrEnum):
    UNKNOWN = 'UNKNOWN'
    LOW = 'LOW'
    MEDIUM = 'MEDIUM'
    HIGH = 'HIGH'


class Status1(StrEnum):
    OPEN = 'OPEN'
    IN_PROGRESS = 'IN_PROGRESS'
    ANSWERED = 'ANSWERED'
    CLOSED = 'CLOSED'


class Question(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    case_id: UUID
    revision: Annotated[int, Field(ge=1)]
    introduced_case_revision: Annotated[int, Field(ge=0)]
    created_at: AwareDatetime
    created_by: Annotated[str, Field(max_length=200, min_length=1)]
    kind: Literal['Question']
    text: Annotated[str, Field(max_length=20000, min_length=1)]
    scenario_ids: Annotated[list[UUID], Field(max_length=10, min_length=1)]
    outcomes: Annotated[list[Outcome], Field(max_length=10, min_length=2)]
    source_to_check: Annotated[str, Field(max_length=20000, min_length=1)]
    limitations: Annotated[list[Limitation], Field(max_length=10000, min_length=0)]
    effort: Effort
    status: Status1
    answer_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]


class Origin2(StrEnum):
    SOURCE_BOUND = 'SOURCE_BOUND'
    AI_SYNTHETIC = 'AI_SYNTHETIC'


class UnknownActorLabel(RootModel[str]):
    root: Annotated[str, Field(max_length=200, min_length=1)]


class ScenarioStep(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    origin: Origin2
    description: Annotated[str, Field(max_length=20000, min_length=1)]
    occurrence: Time
    source_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    assumptions: Annotated[list[Assumption], Field(max_length=10000, min_length=0)]
    actor_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    unknown_actor_labels: Annotated[
        list[UnknownActorLabel], Field(max_length=10000, min_length=0)
    ]


class OrderingItem(RootModel[str]):
    root: Annotated[str, Field(max_length=200, min_length=1)]


class IndependenceAssumption(RootModel[str]):
    root: Annotated[str, Field(max_length=20000, min_length=1)]


class Signature(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mechanism: Annotated[str, Field(max_length=200, min_length=1)]
    ordering: Annotated[list[OrderingItem], Field(max_length=10000, min_length=0)]
    actor_structure: Annotated[str, Field(max_length=200, min_length=1)]
    relaxed_premise_ids: Annotated[list[UUID], Field(max_length=10000, min_length=0)]
    independence_assumptions: Annotated[
        list[IndependenceAssumption], Field(max_length=10000, min_length=0)
    ]


class Family(StrEnum):
    MINIMAL_ASSUMPTIONS = 'MINIMAL_ASSUMPTIONS'
    SOFT_TIME_ERROR = 'SOFT_TIME_ERROR'
    INTERPRETATION_ERROR = 'INTERPRETATION_ERROR'
    UNKNOWN_ACTOR = 'UNKNOWN_ACTOR'
    INDEPENDENT_EVENTS = 'INDEPENDENT_EVENTS'
    OPPORTUNISTIC = 'OPPORTUNISTIC'
    ALTERNATE_ORDER = 'ALTERNATE_ORDER'
    CONVENTIONAL = 'CONVENTIONAL'
    ADVERSARIAL = 'ADVERSARIAL'
    WILDCARD = 'WILDCARD'


class Validation(StrEnum):
    PENDING = 'PENDING'
    PASSED = 'PASSED'
    HELD = 'HELD'
    REJECTED = 'REJECTED'


class Scenario(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    case_id: UUID
    revision: Annotated[int, Field(ge=1)]
    introduced_case_revision: Annotated[int, Field(ge=0)]
    created_at: AwareDatetime
    created_by: Annotated[str, Field(max_length=200, min_length=1)]
    kind: Literal['Scenario']
    run_id: UUID
    tier: Literal['SPECULATIVE']
    origin: Literal['AI_SYNTHETIC']
    review: Review
    title: Annotated[str, Field(max_length=200, min_length=1)]
    summary: Annotated[str, Field(max_length=20000, min_length=1)]
    family: Family
    signature: Signature
    anchor_refs: Annotated[list[Ref], Field(max_length=10000, min_length=1)]
    steps: Annotated[list[ScenarioStep], Field(max_length=100, min_length=1)]
    counter_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    question_ids: Annotated[list[UUID], Field(max_length=10000, min_length=1)]
    validation: Validation


class Task(StrEnum):
    EXTRACT = 'EXTRACT'
    LENS = 'LENS'
    AHA = 'AHA'
    CONTRADICTION = 'CONTRADICTION'
    SURPRISE = 'SURPRISE'


class ModelDigest(RootModel[str]):
    root: Annotated[str, Field(max_length=200, min_length=1)]


class OutputSha256(RootModel[str]):
    root: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]


class Seed(RootModel[int]):
    root: Annotated[int, Field(ge=0)]


class Status2(StrEnum):
    QUEUED = 'QUEUED'
    RUNNING = 'RUNNING'
    SUCCEEDED = 'SUCCEEDED'
    PARTIAL = 'PARTIAL'
    FAILED = 'FAILED'
    CANCELLED = 'CANCELLED'


class ValidationError(RootModel[str]):
    root: Annotated[str, Field(max_length=20000, min_length=1)]


class ModelRun(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    case_id: UUID
    revision: Annotated[int, Field(ge=1)]
    introduced_case_revision: Annotated[int, Field(ge=0)]
    created_at: AwareDatetime
    created_by: Annotated[str, Field(max_length=200, min_length=1)]
    kind: Literal['ModelRun']
    task: Task
    case_revision: Annotated[int, Field(ge=0)]
    provider: Annotated[str, Field(max_length=200, min_length=1)]
    model: Annotated[str, Field(max_length=200, min_length=1)]
    model_digest: ModelDigest | None
    prompt_version: Annotated[str, Field(max_length=200, min_length=1)]
    input_sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]
    output_sha256: OutputSha256 | None
    temperature: Annotated[float, Field(ge=0.0, le=2.0)]
    seed: Seed | None
    status: Status2
    validation_errors: Annotated[
        list[ValidationError], Field(max_length=10000, min_length=0)
    ]
    context_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    omitted_count: Annotated[int, Field(ge=0)]


class ReviewAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    case_id: UUID
    revision: Annotated[int, Field(ge=1)]
    introduced_case_revision: Annotated[int, Field(ge=0)]
    created_at: AwareDatetime
    created_by: Annotated[str, Field(max_length=200, min_length=1)]
    kind: Literal['ReviewAction']
    action: Annotated[str, Field(max_length=200, min_length=1)]
    target_refs: Annotated[list[Ref], Field(max_length=10000, min_length=1)]
    reason: Annotated[str, Field(max_length=20000, min_length=1)]
    actor_subject: Annotated[str, Field(max_length=200, min_length=1)]


class Action(StrEnum):
    RECEIVED = 'RECEIVED'
    VERIFIED = 'VERIFIED'
    EXPORTED = 'EXPORTED'
    TRANSFER_RECORDED = 'TRANSFER_RECORDED'


class CustodyEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    case_id: UUID
    revision: Annotated[int, Field(ge=1)]
    introduced_case_revision: Annotated[int, Field(ge=0)]
    created_at: AwareDatetime
    created_by: Annotated[str, Field(max_length=200, min_length=1)]
    kind: Literal['CustodyEvent']
    evidence: Ref
    action: Action
    sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]
    actor_subject: Annotated[str, Field(max_length=200, min_length=1)]
    details: Annotated[str, Field(max_length=20000, min_length=1)]


class PreviousSha256(RootModel[str]):
    root: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]


class AuditEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    case_id: UUID
    sequence: Annotated[int, Field(ge=1)]
    at: AwareDatetime
    actor: Annotated[str, Field(max_length=200, min_length=1)]
    action: Annotated[str, Field(max_length=200, min_length=1)]
    target_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    reason: Annotated[str, Field(max_length=20000, min_length=1)]
    previous_sha256: PreviousSha256 | None
    payload_sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]


class SceneObject(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    case_id: UUID
    revision: Annotated[int, Field(ge=1)]
    introduced_case_revision: Annotated[int, Field(ge=0)]
    created_at: AwareDatetime
    created_by: Annotated[str, Field(max_length=200, min_length=1)]
    kind: Literal['SceneObject']
    tier: Tier
    origin: Origin
    review: Review
    citations: Annotated[list[Citation], Field(max_length=10000, min_length=0)]
    support_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    counter_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    rationale: Annotated[str, Field(max_length=20000, min_length=1)]
    label: Annotated[str, Field(max_length=200, min_length=1)]
    frame_id: UUID
    units: Literal['METERS']
    schematic: bool
    geometry_sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]
    position: Annotated[list[float], Field(max_length=3, min_length=3)]
    rotation_quaternion: Annotated[list[float], Field(max_length=4, min_length=4)]
    uncertainty_radius_m: Annotated[float, Field(ge=0.0)]


class Anchor(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    case_id: UUID
    revision: Annotated[int, Field(ge=1)]
    introduced_case_revision: Annotated[int, Field(ge=0)]
    created_at: AwareDatetime
    created_by: Annotated[str, Field(max_length=200, min_length=1)]
    kind: Literal['Anchor']
    proposition: Ref
    reason: Annotated[str, Field(max_length=20000, min_length=1)]
    active: bool


class EntityMerge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    case_id: UUID
    revision: Annotated[int, Field(ge=1)]
    introduced_case_revision: Annotated[int, Field(ge=0)]
    created_at: AwareDatetime
    created_by: Annotated[str, Field(max_length=200, min_length=1)]
    kind: Literal['EntityMerge']
    entity_refs: Annotated[list[Ref], Field(max_length=10000, min_length=2)]
    canonical_ref: Ref
    reason: Annotated[str, Field(max_length=20000, min_length=1)]
    active: bool


class Filter1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field: Literal['text']
    op: Literal['contains']
    value: Annotated[str, Field(max_length=20000, min_length=1)]


class Filter2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field: Literal['tier']
    op: Literal['in']
    value: Annotated[list[Tier], Field(max_length=4, min_length=1)]


class ValueEnum(StrEnum):
    PERSON = 'PERSON'
    ORGANIZATION = 'ORGANIZATION'
    PLACE = 'PLACE'
    OBJECT = 'OBJECT'
    VEHICLE = 'VEHICLE'
    DEVICE = 'DEVICE'
    UNKNOWN_ACTOR = 'UNKNOWN_ACTOR'


class Filter3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field: Literal['entity_type']
    op: Literal['in']
    value: Annotated[list[ValueEnum], Field(max_length=7, min_length=1)]


class Filter4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field: Literal['occurrence']
    op: Literal['overlaps']
    start: AwareDatetime
    end: AwareDatetime


class FieldModel(StrEnum):
    cited_source = 'cited_source'
    depends_on = 'depends_on'
    exclude_source = 'exclude_source'


class Filter5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    field: FieldModel
    op: Literal['eq']
    value: UUID


class Filter(RootModel[Filter1 | Filter2 | Filter3 | Filter4 | Filter5]):
    root: Filter1 | Filter2 | Filter3 | Filter4 | Filter5


class Combine(StrEnum):
    all = 'all'
    any = 'any'


class LensPlan(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    query: Annotated[str, Field(max_length=2000, min_length=1)]
    case_revision: Annotated[int, Field(ge=0)]
    combine: Combine
    filters: Annotated[list[Filter], Field(max_length=20, min_length=0)]
    hops: Annotated[int, Field(ge=0, le=2)]
    relations: Annotated[list[Relation], Field(max_length=8, min_length=0)]
    include_similarity: bool
    max_nodes: Annotated[int, Field(ge=1, le=500)]
    max_edges: Annotated[int, Field(ge=0, le=1500)]


class Category(StrEnum):
    EVIDENTIARY = 'EVIDENTIARY'
    CONTEXTUAL = 'CONTEXTUAL'
    SIMILARITY = 'SIMILARITY'


class LensMatch(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    category: Category
    record_refs: Annotated[list[Ref], Field(max_length=10000, min_length=1)]
    edge_ref: Ref | None
    why: Annotated[str, Field(max_length=20000, min_length=1)]
    citations: Annotated[list[Citation], Field(max_length=10000, min_length=1)]
    method: Annotated[str, Field(max_length=200, min_length=1)]


class Warning(RootModel[str]):
    root: Annotated[str, Field(max_length=20000, min_length=1)]


class LensResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    case_revision: Annotated[int, Field(ge=0)]
    index_revision: Annotated[int, Field(ge=0)]
    node_ids: Annotated[list[UUID], Field(max_length=10000, min_length=0)]
    edge_ids: Annotated[list[UUID], Field(max_length=10000, min_length=0)]
    matches: Annotated[list[LensMatch], Field(max_length=10000, min_length=0)]
    truncated: bool
    omitted_count: Annotated[int, Field(ge=0)]
    warnings: Annotated[list[Warning], Field(max_length=10000, min_length=0)]


class AhaRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    case_revision: Annotated[int, Field(ge=0)]
    interval: Time
    anchor_refs: Annotated[list[Ref], Field(max_length=1000, min_length=1)]
    soft_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    exclude_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    requested_count: Annotated[int, Field(ge=1, le=10)]
    families: Annotated[list[Family], Field(max_length=10, min_length=1)]
    constraint_refs: Annotated[list[Ref], Field(max_length=1000, min_length=0)]


class PartialReason(RootModel[str]):
    root: Annotated[str, Field(max_length=20000, min_length=1)]


class AhaResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    run: ModelRun
    scenarios: Annotated[list[Scenario], Field(max_length=10, min_length=0)]
    questions: Annotated[list[Question], Field(max_length=10000, min_length=0)]
    requested_count: Annotated[int, Field(ge=1, le=10)]
    rejected_count: Annotated[int, Field(ge=0)]
    partial_reason: PartialReason | None


class ExtractionResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    proposals: Annotated[
        list[Entity | Observation | Event | Interpretation | Edge | Contradiction],
        Field(max_length=10000, min_length=0),
    ]
    warnings: Annotated[list[Warning], Field(max_length=10000, min_length=0)]


class Decision(StrEnum):
    ACCEPT = 'ACCEPT'
    REJECT = 'REJECT'


class Command2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['reviewProposal']
    proposal_id: UUID
    decision: Decision
    reason: Annotated[str, Field(max_length=20000, min_length=1)]


class TargetState(StrEnum):
    PROPOSED = 'PROPOSED'
    TESTING = 'TESTING'
    SUPPORTED = 'SUPPORTED'
    WEAKENED = 'WEAKENED'
    RETIRED = 'RETIRED'


class Command3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['transitionHypothesis']
    hypothesis: Ref
    target_state: TargetState
    reason: Annotated[str, Field(max_length=20000, min_length=1)]
    evidence_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]


class Command4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['reopenHypothesis']
    hypothesis: Ref
    new_evidence_refs: Annotated[list[Ref], Field(max_length=10000, min_length=1)]
    reason: Annotated[str, Field(max_length=20000, min_length=1)]


class Decision1(StrEnum):
    UNRESOLVED = 'UNRESOLVED'
    RESOLVED = 'RESOLVED'
    DISMISSED = 'DISMISSED'


class Command5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['decideContradiction']
    contradiction: Ref
    decision: Decision1
    evidence_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    reason: Annotated[str, Field(max_length=20000, min_length=1)]


class Command6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['setAnchor']
    proposition: Ref
    active: bool
    reason: Annotated[str, Field(max_length=20000, min_length=1)]


class Command7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['excludeSource']
    source: Ref
    excluded: bool
    reason: Annotated[str, Field(max_length=20000, min_length=1)]


class Status3(Enum):
    OPEN = 'OPEN'
    IN_PROGRESS = 'IN_PROGRESS'
    ANSWERED = 'ANSWERED'
    CLOSED = 'CLOSED'


class Command10(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['answerQuestion']
    question: Ref
    status: Status3
    answer_refs: list[Ref]
    reason: Annotated[str, Field(max_length=20000, min_length=1)]


class CommandResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    case_revision: Annotated[int, Field(ge=0)]
    changed_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    proposal_id: UUID | None
    audit_sequence: Annotated[int, Field(ge=1)]


class Type(StrEnum):
    INGEST = 'INGEST'
    EXTRACT = 'EXTRACT'
    LENS = 'LENS'
    AHA = 'AHA'
    EXPORT = 'EXPORT'
    BACKUP = 'BACKUP'
    IMPORT = 'IMPORT'
    VERIFY = 'VERIFY'
    REINDEX = 'REINDEX'
    SURPRISE = 'SURPRISE'


class State1(StrEnum):
    QUEUED = 'QUEUED'
    RUNNING = 'RUNNING'
    SUCCEEDED = 'SUCCEEDED'
    FAILED = 'FAILED'
    CANCELLED = 'CANCELLED'


class Fraction(RootModel[float]):
    root: Annotated[float, Field(ge=0.0, le=1.0)]


class ResultPath(RootModel[str]):
    root: Annotated[str, Field(max_length=200, min_length=1)]


class Error(RootModel[str]):
    root: Annotated[str, Field(max_length=20000, min_length=1)]


class Job(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    case_id: UUID
    type: Type
    state: State1
    phase: Annotated[str, Field(max_length=200, min_length=1)]
    fraction: Fraction | None
    result_path: ResultPath | None
    error: Error | None
    snapshot_revision: Annotated[int, Field(ge=0)]


class Format(StrEnum):
    PDF = 'PDF'
    HTML = 'HTML'
    JSON = 'JSON'
    CSV = 'CSV'
    CASE_ZIP = 'CASE_ZIP'


class Section(StrEnum):
    CHRONOLOGY = 'CHRONOLOGY'
    CONTRADICTIONS = 'CONTRADICTIONS'
    QUESTIONS = 'QUESTIONS'
    NOTES = 'NOTES'
    SCENARIOS = 'SCENARIOS'
    SOURCES = 'SOURCES'
    HISTORY = 'HISTORY'


class ExportRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    format: Format
    sections: Annotated[list[Section], Field(max_length=7, min_length=1)]
    case_revision: Annotated[int, Field(ge=0)]
    include_synthetic: bool
    redaction_plan_id: UUID | None


class File(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        regex_engine="python-re",
    )
    path: Annotated[str, Field(pattern='^(?!/)(?!.*\\.\\.)[^\\\\]+$')]
    bytes: Annotated[int, Field(ge=0)]
    sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]


class Manifest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['1.0.0']
    case_id: UUID
    case_revision: Annotated[int, Field(ge=0)]
    synthetic: bool
    files: Annotated[list[File], Field(max_length=10000, min_length=1)]


class ImportEnvelope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    case_id: UUID
    authenticated_sender: Annotated[str, Field(max_length=200, min_length=1)]
    mailbox_id: Annotated[str, Field(max_length=200, min_length=1)]
    message_id: Annotated[str, Field(max_length=200, min_length=1)]
    message_sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]
    attachment_evidence_ids: Annotated[
        list[UUID], Field(max_length=10000, min_length=0)
    ]
    received_at: AwareDatetime


class FieldError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    path: Annotated[str, Field(max_length=200, min_length=1)]
    code: Annotated[str, Field(max_length=200, min_length=1)]
    message: Annotated[str, Field(max_length=20000, min_length=1)]


class Error1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: Annotated[str, Field(max_length=200, min_length=1)]
    message: Annotated[str, Field(max_length=20000, min_length=1)]
    request_id: Annotated[str, Field(max_length=200, min_length=1)]
    field_errors: Annotated[list[FieldError], Field(max_length=10000, min_length=0)]
    retryable: bool


class CreateCase(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: Annotated[str, Field(max_length=200, min_length=1)]
    timezone: Annotated[str, Field(max_length=200, min_length=1)]
    synthetic: bool


class QueryRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    query: Annotated[str, Field(max_length=2000, min_length=1)]
    case_revision: Annotated[int, Field(ge=0)]


class NextCursor(RootModel[str]):
    root: Annotated[str, Field(max_length=20000, min_length=1)]


class CasePage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    items: Annotated[list[Case], Field(max_length=200, min_length=0)]
    next_cursor: NextCursor | None


class Mode(StrEnum):
    field_2D = '2D'
    field_3D = '3D'
    TABLE = 'TABLE'


class Pin(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    x: float
    y: float
    z: float


class SavedView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    view_revision: Annotated[int, Field(ge=1)]
    title: Annotated[str, Field(max_length=200, min_length=1)]
    plan: LensPlan
    mode: Mode
    pins: Annotated[list[Pin], Field(max_length=10000, min_length=0)]


class Region(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    evidence_id: UUID
    locator: Locator


class RedactionPlan(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    case_revision: Annotated[int, Field(ge=0)]
    reason: Annotated[str, Field(max_length=20000, min_length=1)]
    remove_record_ids: Annotated[list[UUID], Field(max_length=10000, min_length=0)]
    regions: Annotated[list[Region], Field(max_length=10000, min_length=0)]
    reviewed: bool


class Status4(StrEnum):
    OK = 'OK'
    DEGRADED = 'DEGRADED'


class Health(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Status4
    schema_version: Annotated[str, Field(max_length=200, min_length=1)]
    offline_mode: bool


class SessionRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    pairing_secret: Annotated[str, Field(max_length=200, min_length=1)]
    operator_label: Annotated[str, Field(max_length=200, min_length=1)]


class Session(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    actor: Annotated[str, Field(max_length=200, min_length=1)]
    csrf_token: Annotated[str, Field(max_length=200, min_length=1)]
    expires_at: AwareDatetime


class ConstraintType(StrEnum):
    INTERVAL = 'INTERVAL'
    BEFORE = 'BEFORE'


class MinLagSeconds(RootModel[float]):
    root: Annotated[float, Field(ge=0.0)]


class MaxLagSeconds(RootModel[float]):
    root: Annotated[float, Field(ge=0.0)]


class TemporalConstraint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    case_id: UUID
    revision: Annotated[int, Field(ge=1)]
    introduced_case_revision: Annotated[int, Field(ge=0)]
    created_at: AwareDatetime
    created_by: Annotated[str, Field(max_length=200, min_length=1)]
    kind: Literal['TemporalConstraint']
    constraint_type: ConstraintType
    left: Ref
    right: Ref | None
    window: Time | None
    min_lag_seconds: MinLagSeconds | None
    max_lag_seconds: MaxLagSeconds | None
    strict: bool
    basis_refs: Annotated[list[Ref], Field(max_length=10000, min_length=1)]
    review: Review
    rationale: Annotated[str, Field(max_length=20000, min_length=1)]


class ClockCorrection(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    case_id: UUID
    revision: Annotated[int, Field(ge=1)]
    introduced_case_revision: Annotated[int, Field(ge=0)]
    created_at: AwareDatetime
    created_by: Annotated[str, Field(max_length=200, min_length=1)]
    kind: Literal['ClockCorrection']
    clock_id: Annotated[str, Field(max_length=200, min_length=1)]
    raw_time_refs: Annotated[list[Ref], Field(max_length=10000, min_length=1)]
    offset_min_seconds: float
    offset_max_seconds: float
    basis_refs: Annotated[list[Ref], Field(max_length=10000, min_length=1)]
    review: Review
    rationale: Annotated[str, Field(max_length=20000, min_length=1)]


class NoteType(StrEnum):
    INVESTIGATOR_NOTE = 'INVESTIGATOR_NOTE'
    SCOPE_LIMIT = 'SCOPE_LIMIT'
    DECISION_NOTE = 'DECISION_NOTE'


class Note(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    case_id: UUID
    revision: Annotated[int, Field(ge=1)]
    introduced_case_revision: Annotated[int, Field(ge=0)]
    created_at: AwareDatetime
    created_by: Annotated[str, Field(max_length=200, min_length=1)]
    kind: Literal['Note']
    text: Annotated[str, Field(max_length=20000, min_length=1)]
    target_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    review: Review
    note_type: NoteType


class Snapshot(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    case_id: UUID
    case_revision: Annotated[int, Field(ge=0)]
    record_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    anchor_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    constraint_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    retired_hypothesis_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    source_manifest_sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]
    created_at: AwareDatetime


class Adapter(StrEnum):
    REPLAY = 'REPLAY'
    OLLAMA = 'OLLAMA'
    OPENAI_COMPATIBLE_LOCAL = 'OPENAI_COMPATIBLE_LOCAL'
    REMOTE_OPTIONAL = 'REMOTE_OPTIONAL'


class SecretRef(RootModel[str]):
    root: Annotated[str, Field(max_length=200, min_length=1)]


class ProviderConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    label: Annotated[str, Field(max_length=200, min_length=1)]
    adapter: Adapter
    base_url: AnyUrl
    model: Annotated[str, Field(max_length=200, min_length=1)]
    remote: bool
    enabled: bool
    secret_ref: SecretRef | None
    context_tokens: Annotated[int, Field(ge=1)]
    max_output_tokens: Annotated[int, Field(ge=1)]
    timeout_seconds: Annotated[int, Field(ge=1, le=600)]


class ProviderStatus(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    available: bool
    structured_output: bool
    embeddings: bool
    model_digest: ModelDigest | None
    message: Annotated[str, Field(max_length=20000, min_length=1)]


class CasePolicy(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    remote_models_enabled: bool
    approved_provider_ids: Annotated[list[UUID], Field(max_length=10000, min_length=0)]
    export_names_in_filenames: bool


class IngestSummary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    result_type: Literal['INGEST']
    evidence_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    derivative_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    proposal_ids: Annotated[list[UUID], Field(max_length=10000, min_length=0)]
    warnings: Annotated[list[Warning], Field(max_length=10000, min_length=0)]


class ExportArtifact(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    result_type: Literal['EXPORT']
    export_id: UUID
    sha256: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]
    bytes: Annotated[int, Field(ge=0)]
    case_revision: Annotated[int, Field(ge=0)]
    expires_at: AwareDatetime


class ResultType(StrEnum):
    VERIFY = 'VERIFY'
    REINDEX = 'REINDEX'
    IMPORT = 'IMPORT'


class Failure(RootModel[str]):
    root: Annotated[str, Field(max_length=20000, min_length=1)]


class VerificationResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    result_type: ResultType
    case_revision: Annotated[int, Field(ge=0)]
    checked_count: Annotated[int, Field(ge=0)]
    failures: Annotated[list[Failure], Field(max_length=10000, min_length=0)]
    warnings: Annotated[list[Warning], Field(max_length=10000, min_length=0)]


class JobEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    event_id: Annotated[int, Field(ge=1)]
    job_id: UUID
    at: AwareDatetime
    state: State1
    phase: Annotated[str, Field(max_length=200, min_length=1)]
    fraction: Fraction | None


class RunResult(
    RootModel[
        AhaResult
        | ExtractionResult
        | LensPlan
        | IngestSummary
        | ExportArtifact
        | VerificationResult
    ]
):
    root: (
        AhaResult
        | ExtractionResult
        | LensPlan
        | IngestSummary
        | ExportArtifact
        | VerificationResult
    )


class QuestionKey(RootModel[str]):
    root: Annotated[str, Field(pattern='^[A-Za-z][A-Za-z0-9_-]{0,39}$')]


class ModelScenarioProposal(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: Annotated[str, Field(max_length=200, min_length=1)]
    summary: Annotated[str, Field(max_length=20000, min_length=1)]
    family: Family
    signature: Signature
    anchor_refs: Annotated[list[Ref], Field(max_length=10000, min_length=1)]
    steps: Annotated[list[ScenarioStep], Field(max_length=100, min_length=1)]
    counter_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    candidate_key: Annotated[str, Field(pattern='^[A-Za-z][A-Za-z0-9_-]{0,39}$')]
    question_keys: Annotated[list[QuestionKey], Field(max_length=30, min_length=1)]


class SupportsScenarioKey(RootModel[str]):
    root: Annotated[str, Field(pattern='^[A-Za-z][A-Za-z0-9_-]{0,39}$')]


class WeakensScenarioKey(RootModel[str]):
    root: Annotated[str, Field(pattern='^[A-Za-z][A-Za-z0-9_-]{0,39}$')]


class Outcome1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    observation: Annotated[str, Field(max_length=20000, min_length=1)]
    supports_scenario_keys: Annotated[
        list[SupportsScenarioKey], Field(max_length=100, min_length=0)
    ]
    weakens_scenario_keys: Annotated[
        list[WeakensScenarioKey], Field(max_length=100, min_length=0)
    ]


class ScenarioKey(RootModel[str]):
    root: Annotated[str, Field(pattern='^[A-Za-z][A-Za-z0-9_-]{0,39}$')]


class ModelQuestionProposal(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: Annotated[str, Field(max_length=20000, min_length=1)]
    outcomes: Annotated[list[Outcome1], Field(max_length=10, min_length=2)]
    source_to_check: Annotated[str, Field(max_length=20000, min_length=1)]
    limitations: Annotated[list[Limitation], Field(max_length=10000, min_length=0)]
    effort: Effort
    question_key: Annotated[str, Field(pattern='^[A-Za-z][A-Za-z0-9_-]{0,39}$')]
    scenario_keys: Annotated[list[ScenarioKey], Field(max_length=10, min_length=1)]


class ModelAhaOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    scenarios: Annotated[
        list[ModelScenarioProposal], Field(max_length=10, min_length=0)
    ]
    questions: Annotated[
        list[ModelQuestionProposal], Field(max_length=100, min_length=0)
    ]
    partial_reason: Annotated[str | None, Field(max_length=20000)]


class ModelEntityProposal(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['Entity']
    label: Annotated[str, Field(max_length=200, min_length=1)]
    entity_type: EntityType
    aliases: Annotated[list[Alias], Field(max_length=10000, min_length=0)]
    source_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    proposed_id: UUID


class ModelObservationProposal(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['Observation']
    citations: Annotated[list[Citation], Field(max_length=10000, min_length=1)]
    support_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    counter_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    rationale: Annotated[str, Field(max_length=20000, min_length=1)]
    statement: Annotated[str, Field(max_length=20000, min_length=1)]
    subject_refs: Annotated[list[Ref], Field(max_length=10000, min_length=1)]
    predicate: Annotated[str, Field(max_length=200, min_length=1)]
    object_value: Annotated[str, Field(max_length=20000, min_length=1)]
    occurrence: Time
    discovered_at: AwareDatetime | None
    recorded_at: AwareDatetime | None
    provenance_group: Annotated[str, Field(max_length=200, min_length=1)]
    independence: Independence
    suggested_tier: Tier
    proposed_id: UUID


class ModelEventProposal(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['Event']
    citations: Annotated[list[Citation], Field(max_length=10000, min_length=0)]
    support_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    counter_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    rationale: Annotated[str, Field(max_length=20000, min_length=1)]
    label: Annotated[str, Field(max_length=200, min_length=1)]
    occurrence: Time
    participant_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    observation_refs: Annotated[list[Ref], Field(max_length=10000, min_length=1)]
    suggested_tier: Tier
    proposed_id: UUID


class ModelInterpretationProposal(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['Interpretation']
    citations: Annotated[list[Citation], Field(max_length=10000, min_length=0)]
    support_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    counter_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    rationale: Annotated[str, Field(max_length=20000, min_length=1)]
    statement: Annotated[str, Field(max_length=20000, min_length=1)]
    assumptions: Annotated[list[Assumption], Field(max_length=10000, min_length=0)]
    premise_refs: Annotated[list[Ref], Field(max_length=10000, min_length=1)]
    suggested_tier: Tier
    proposed_id: UUID


class ModelEdgeProposal(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['Edge']
    citations: Annotated[list[Citation], Field(max_length=10000, min_length=0)]
    support_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    counter_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    rationale: Annotated[str, Field(max_length=20000, min_length=1)]
    from_ref: Ref
    to_ref: Ref
    relation: Relation
    independence: Independence
    suggested_tier: Tier
    proposed_id: UUID


class Warning4(RootModel[str]):
    root: Annotated[str, Field(max_length=20000)]


class ModelExtractionOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    proposals: Annotated[
        list[
            ModelEntityProposal
            | ModelObservationProposal
            | ModelEventProposal
            | ModelInterpretationProposal
            | ModelEdgeProposal
        ],
        Field(max_length=1000),
    ]
    warnings: Annotated[list[Warning4], Field(max_length=100)]


class ModelContradictionProposal(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    proposition_refs: Annotated[list[Ref], Field(max_length=20, min_length=2)]
    rule: Annotated[str, Field(max_length=200, min_length=1)]
    rule_version: Annotated[str, Field(max_length=200, min_length=1)]
    strength: Strength
    qualifications: Annotated[
        list[Qualification], Field(max_length=10000, min_length=0)
    ]
    resolution_targets: Annotated[
        list[ResolutionTarget], Field(max_length=10000, min_length=1)
    ]


class ModelContradictionOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    proposals: Annotated[list[ModelContradictionProposal], Field(max_length=1000)]
    warnings: Annotated[list[Warning4], Field(max_length=100)]


class HumanEntityDraft(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['Entity']
    label: Annotated[str, Field(max_length=200, min_length=1)]
    entity_type: EntityType
    aliases: Annotated[list[Alias], Field(max_length=10000, min_length=0)]
    source_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]


class HumanObservationDraft(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['Observation']
    tier: Tier
    citations: Annotated[list[Citation], Field(max_length=10000, min_length=1)]
    support_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    counter_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    rationale: Annotated[str, Field(max_length=20000, min_length=1)]
    statement: Annotated[str, Field(max_length=20000, min_length=1)]
    subject_refs: Annotated[list[Ref], Field(max_length=10000, min_length=1)]
    predicate: Annotated[str, Field(max_length=200, min_length=1)]
    object_value: Annotated[str, Field(max_length=20000, min_length=1)]
    occurrence: Time
    discovered_at: AwareDatetime | None
    recorded_at: AwareDatetime | None
    provenance_group: Annotated[str, Field(max_length=200, min_length=1)]
    independence: Independence


class HumanInterpretationDraft(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['Interpretation']
    tier: Tier
    citations: Annotated[list[Citation], Field(max_length=10000, min_length=0)]
    support_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    counter_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    rationale: Annotated[str, Field(max_length=20000, min_length=1)]
    statement: Annotated[str, Field(max_length=20000, min_length=1)]
    assumptions: Annotated[list[Assumption], Field(max_length=10000, min_length=0)]
    premise_refs: Annotated[list[Ref], Field(max_length=10000, min_length=1)]


class HumanEventDraft(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['Event']
    tier: Tier
    citations: Annotated[list[Citation], Field(max_length=10000, min_length=0)]
    support_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    counter_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    rationale: Annotated[str, Field(max_length=20000, min_length=1)]
    label: Annotated[str, Field(max_length=200, min_length=1)]
    occurrence: Time
    participant_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    observation_refs: Annotated[list[Ref], Field(max_length=10000, min_length=1)]


class HumanEdgeDraft(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['Edge']
    tier: Tier
    citations: Annotated[list[Citation], Field(max_length=10000, min_length=0)]
    support_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    counter_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    rationale: Annotated[str, Field(max_length=20000, min_length=1)]
    from_ref: Ref
    to_ref: Ref
    relation: Relation
    independence: Independence


class HumanHypothesisDraft(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['Hypothesis']
    tier: Tier
    citations: Annotated[list[Citation], Field(max_length=10000, min_length=0)]
    support_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    counter_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    rationale: Annotated[str, Field(max_length=20000, min_length=1)]
    claim: Annotated[str, Field(max_length=20000, min_length=1)]
    family_key: Annotated[str, Field(max_length=200, min_length=1)]
    strengthen_if: Annotated[
        list[StrengthenIfItem], Field(max_length=10000, min_length=0)
    ]
    weaken_if: Annotated[list[WeakenIfItem], Field(max_length=10000, min_length=0)]
    retire_if: Annotated[list[RetireIfItem], Field(max_length=10000, min_length=0)]
    falsifiability: Falsifiability


class HumanNoteDraft(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['Note']
    text: Annotated[str, Field(max_length=20000, min_length=1)]
    target_refs: Annotated[list[Ref], Field(max_length=10000, min_length=0)]
    note_type: NoteType


class HumanTemporalConstraintDraft(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['TemporalConstraint']
    constraint_type: ConstraintType
    left: Ref
    right: Ref | None
    window: Time | None
    min_lag_seconds: MinLagSeconds | None
    max_lag_seconds: MaxLagSeconds | None
    strict: bool
    basis_refs: Annotated[list[Ref], Field(max_length=10000, min_length=1)]
    rationale: Annotated[str, Field(max_length=20000, min_length=1)]


class HumanClockCorrectionDraft(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['ClockCorrection']
    clock_id: Annotated[str, Field(max_length=200, min_length=1)]
    raw_time_refs: Annotated[list[Ref], Field(max_length=10000, min_length=1)]
    offset_min_seconds: float
    offset_max_seconds: float
    basis_refs: Annotated[list[Ref], Field(max_length=10000, min_length=1)]
    rationale: Annotated[str, Field(max_length=20000, min_length=1)]


class HumanEntityMergeDraft(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['EntityMerge']
    entity_refs: Annotated[list[Ref], Field(max_length=10000, min_length=2)]
    canonical_ref: Ref
    reason: Annotated[str, Field(max_length=20000, min_length=1)]
    active: bool


class HumanRecordDraft(
    RootModel[
        HumanEntityDraft
        | HumanObservationDraft
        | HumanInterpretationDraft
        | HumanEventDraft
        | HumanEdgeDraft
        | HumanHypothesisDraft
        | HumanNoteDraft
        | HumanTemporalConstraintDraft
        | HumanClockCorrectionDraft
        | HumanEntityMergeDraft
    ]
):
    root: (
        HumanEntityDraft
        | HumanObservationDraft
        | HumanInterpretationDraft
        | HumanEventDraft
        | HumanEdgeDraft
        | HumanHypothesisDraft
        | HumanNoteDraft
        | HumanTemporalConstraintDraft
        | HumanClockCorrectionDraft
        | HumanEntityMergeDraft
    )


class Record(
    RootModel[
        Evidence
        | Derivative
        | Entity
        | Observation
        | Interpretation
        | Event
        | Edge
        | Contradiction
        | Hypothesis
        | Question
        | Scenario
        | ModelRun
        | ReviewAction
        | CustodyEvent
        | SceneObject
        | Anchor
        | EntityMerge
        | TemporalConstraint
        | ClockCorrection
        | Note
    ]
):
    root: (
        Evidence
        | Derivative
        | Entity
        | Observation
        | Interpretation
        | Event
        | Edge
        | Contradiction
        | Hypothesis
        | Question
        | Scenario
        | ModelRun
        | ReviewAction
        | CustodyEvent
        | SceneObject
        | Anchor
        | EntityMerge
        | TemporalConstraint
        | ClockCorrection
        | Note
    )


class CaseExchange(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['1.0.0']
    case: Case
    records: Annotated[list[Record], Field(max_length=10000, min_length=0)]
    audit: Annotated[list[AuditEvent], Field(max_length=10000, min_length=0)]


class Proposal(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    case_revision: Annotated[int, Field(ge=0)]
    record: Record
    status: Review
    run_id: UUID | None


class Command1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['proposeRecord']
    record: HumanRecordDraft
    reason: Annotated[str, Field(max_length=20000, min_length=1)]


class Command8(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['reviseRecord']
    target: Ref
    record: HumanRecordDraft
    reason: Annotated[str, Field(max_length=20000, min_length=1)]


class Command9(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['proposeContradiction']
    proposal: ModelContradictionProposal
    reason: Annotated[str, Field(max_length=20000, min_length=1)]


class Command(
    RootModel[
        Command1
        | Command2
        | Command3
        | Command4
        | Command5
        | Command6
        | Command7
        | Command8
        | Command9
        | Command10
    ]
):
    root: (
        Command1
        | Command2
        | Command3
        | Command4
        | Command5
        | Command6
        | Command7
        | Command8
        | Command9
        | Command10
    )


class Page(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    case_revision: Annotated[int, Field(ge=0)]
    index_revision: Annotated[int, Field(ge=0)]
    items: Annotated[list[Record], Field(max_length=200, min_length=0)]
    next_cursor: NextCursor | None


class GraphResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    case_revision: Annotated[int, Field(ge=0)]
    nodes: Annotated[list[Record], Field(max_length=500, min_length=0)]
    edges: Annotated[list[Edge], Field(max_length=1500, min_length=0)]
    truncated: bool


class AhaBuildContract100(RootModel[CaseExchange]):
    root: Annotated[CaseExchange, Field(title='AHA build contract 1.0.0')]
